In [1]:
import numpy as np

Create a numpy array of int, characters, float and find their shapes

In [2]:
integers = np.random.randint(1,10,10)
print(integers , integers.shape)

[7 7 2 8 6 6 2 6 4 2] (10,)


In [3]:
floats = np.random.random(10)
print(floats , floats.shape)

[0.74635048 0.73699082 0.6175691  0.52667299 0.19211183 0.63399489
 0.82579256 0.44712722 0.86912899 0.62267314] (10,)


In [92]:
chars = np.arange(65,91)
characters = []

for i in range(10): 
    characters.append(chr(np.random.choice(chars)))

characters

['J', 'P', 'Y', 'A', 'C', 'H', 'P', 'C', 'I', 'B']

Create a zeros, empty, identity , eye and a full array

In [4]:
zeros = np.zeros(shape=(10,10))
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
empty = np.empty(10)
empty

array([0.74635048, 0.73699082, 0.6175691 , 0.52667299, 0.19211183,
       0.63399489, 0.82579256, 0.44712722, 0.86912899, 0.62267314])

In [6]:
identity = np.identity(10)
identity

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [7]:
eye = np.eye(10,8)
eye

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
full = np.full((8,2),10)
full

array([[10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10]])

Declare an array having the datatype of object, is it possible?

In [18]:
objects = np.array([1,'shaffay','m',10.1],dtype=object)
objects

array([1, 'shaffay', 'm', 10.1], dtype=object)

Create an array having 5 equally spaced numbers ranging from 5 to 15

In [10]:
array = np.linspace(5,15,5)
array

array([ 5. ,  7.5, 10. , 12.5, 15. ])

Create a numpy array ranging from 1 to 100.

In [11]:
array = np.arange(1,101)
array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

Reshape the above array into (100,15). Is it possible?

In [12]:
array = array.reshape(100,15)
array

ValueError: cannot reshape array of size 100 into shape (100,15)

Reshape the array into (100,10).

In [13]:
array = array.reshape(10,10)
array

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

Flatten and ravel the reshaped array. What is the difference?

In [14]:
# Flatten creates deepcopy
flatten = array.flatten()
flatten

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [15]:
# Ravel creates shallowcopy
ravel = array.ravel()
ravel

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

Take an array [[1 2 3] [4 5 6] [ 7 8 9]]. Sum it along 0 and 1 axis

In [24]:
array =  np.array([[1, 2, 3], [4, 5, 6], [ 7, 8, 9]])

print("Suming columns : " , np.sum(array,axis=0))
print("Summing rows : " , np.sum(array,axis=1))

Suming columns :  [12 15 18]
Summing rows :  [ 6 15 24]


Find the number of bytes used by your array

In [25]:
array.nbytes

72

Find the maximum and minimum values in a 1D array.

In [28]:
array = np.linspace(5,15,5)
print("Minimum : " , np.min(array))
print("Maximum : " , np.max(array))

Minimum :  5.0
Maximum :  15.0


Find the maximum and minimum values in 2D array

In [32]:
array =  np.array([[1, 2, 3], [4, 5, 6], [ 7, 8, 9]])

print("Minimum (Col): " , np.min(array , axis=0))
print("Minimum (Row): " , np.min(array , axis=1))

print("Maximum (Col): " , np.max(array , axis=0))
print("Maximum (Row): " , np.max(array , axis=1))

Minimum (Col):  [1 2 3]
Minimum (Row):  [1 4 7]
Maximum (Col):  [7 8 9]
Maximum (Row):  [3 6 9]


Sort an array

In [35]:
array = np.random.randint(1,10,10)
print("Unsorted : " , array)
print("Sorted : " , np.sort(array))

Unsorted :  [4 8 5 5 4 6 7 7 6 3]
Sorted :  [3 4 4 5 5 6 6 7 7 8]


Is * and mul the same as dot product for numpy arrays and matrices? Check.

In [76]:
array1 = np.linspace(5,15,5)
array2 = np.linspace(5,15,5)

In [77]:
print(array1 * array2)

[ 25.    56.25 100.   156.25 225.  ]


In [78]:
print(array1.dot(array2))

562.5


Not Equal. Dimensions are different

Take the square root and norm of an array.

In [39]:
print("Array : " , array)
print("\nSquare Root : " , np.sqrt(array))
print("\nNormalize: " , np.linalg.norm(array))

Array :  [4 8 5 5 4 6 7 7 6 3]

Square Root :  [2.         2.82842712 2.23606798 2.23606798 2.         2.44948974
 2.64575131 2.64575131 2.44948974 1.73205081]

Normalize:  18.027756377319946


Find the std, non-zero, zero values and mean of an array.

In [46]:
print("Array : " , array)

print("\nStandard Deviation : " , np.std(array))
print("\nMean : " , np.mean(array))

print("\nNon Zeros : " , array[array != 0])
print("\nZeros : " , array[array == 0])

Array :  [4 8 5 5 4 6 7 7 6 3]

Standard Deviation :  1.5

Mean :  5.5

Non Zeros :  [4 8 5 5 4 6 7 7 6 3]

Zeros :  []


Convert some angles to radians and vice versa.

In [48]:
array

array([4, 8, 5, 5, 4, 6, 7, 7, 6, 3])

In [49]:
angles = np.degrees(array)
angles

array([229.18311805, 458.3662361 , 286.47889757, 286.47889757,
       229.18311805, 343.77467708, 401.07045659, 401.07045659,
       343.77467708, 171.88733854])

In [51]:
radians = np.radians(array)
radians

array([0.06981317, 0.13962634, 0.08726646, 0.08726646, 0.06981317,
       0.10471976, 0.12217305, 0.12217305, 0.10471976, 0.05235988])

Save and load some of your arrays

In [54]:
np.save('array',array)

In [65]:
np.load('array.npy')

array([4, 8, 5, 5, 4, 6, 7, 7, 6, 3])

Calculate the mean, std, var, max, min, of an array with shape (3,3,12,3) containing floats drawn
from a normal distribution with mean 21 and sigma 4.5. see the np.random.normal.

In [75]:
array = np.random.normal(21,4.5,[3,3,12,3])
array

array([[[[27.66231469, 22.30024806, 23.49231014],
         [21.20819386, 27.9379371 , 14.64658379],
         [14.51822837, 21.9698745 , 21.15125184],
         [22.89218056, 12.29845875, 14.50426187],
         [18.94859757, 22.94503226, 16.76891088],
         [17.08067483, 24.32358799, 14.73530435],
         [20.54114838, 25.59124561, 22.2847025 ],
         [19.76041969, 27.05557942, 18.92232841],
         [26.67130034, 20.85298673, 25.40622758],
         [16.42642291, 32.09270846, 16.22606011],
         [20.9425334 , 18.7242066 , 14.80774347],
         [11.66892478, 13.73629999, 14.69366101]],

        [[24.0895022 , 25.09397001, 20.45014599],
         [18.15474379, 20.50721673, 24.27735967],
         [17.83557606, 24.27374154, 16.76540112],
         [29.01695348, 24.14026275, 19.30640965],
         [24.05985169, 17.84000415, 26.99102736],
         [27.81748125, 24.29391899, 19.77393944],
         [21.76519578, 19.91628445, 22.49088538],
         [28.89583294, 30.57375373, 22.23021239]

In [68]:
np.mean(array)

21.064443044639358

In [69]:
np.std(array)

4.470150274375113

In [70]:
np.max(array)

36.20327077198603

In [71]:
np.min(array)

6.97846870317651

In [72]:
np.var(array)

19.9822434754959