You and your friend are standing in front of a magician and he has a basket with 6 white,
4 red and 5 blue balls, each time the magician draws 3 balls and asks you to predict
what would be the color of the balls. If you predict correctly the magician loses the
game and you win. Since you have become a statistician after doing the ML assignment,
what should be the optimal color scheme of the balls that you would propose in order
to win the game?

In [1]:
import math

In [2]:
array = ['w','r','b']

combinations = []

for i in array:
    for j in array:
        for k in array:
            
            combination = i + j + k
            combinations.append(combination)

In [3]:
probabilities = []

for i in combinations:
    
    w , r , b  = 0 , 0 , 0
    
    for j in i:
        if j == 'w':
            w += 1
        elif j == 'r':
            r += 1        
        elif j == 'b':
            b += 1
            
    comb_1 = math.comb(6, w)           
    comb_2 = math.comb(4, r)  
    comb_3 = math.comb(5, b)
    comb_4 = math.comb(15, 3)
    
    probabilities.append((comb_1 * comb_2 * comb_3) / comb_4)

In [4]:
index = 0
maxi = 0

for i , value in enumerate(probabilities):
    
    if value > maxi:
        maxi = value
        index = i

print(probabilities[index])
print(combinations[index])

0.26373626373626374
wrb


Write a function that takes input from user and determines the input parameters belong
which class (using Naïve assumptions) (use the provided dataset) . Compare your results
with GaussianNB() built in function

In [5]:
import numpy as np
import pandas as pd

In [16]:
data = pd.read_csv("iris.data")
data.columns=['SepalLength','SepalWidth','PetalLength','PetalWidth','Class']
data

SepalLength  SepalWidth  PetalLength  PetalWidth           Class
0            4.9         3.0          1.4         0.2     Iris-setosa
1            4.7         3.2          1.3         0.2     Iris-setosa
2            4.6         3.1          1.5         0.2     Iris-setosa
3            5.0         3.6          1.4         0.2     Iris-setosa
4            5.4         3.9          1.7         0.4     Iris-setosa
..           ...         ...          ...         ...             ...
144          6.7         3.0          5.2         2.3  Iris-virginica
145          6.3         2.5          5.0         1.9  Iris-virginica
146          6.5         3.0          5.2         2.0  Iris-virginica
147          6.2         3.4          5.4         2.3  Iris-virginica
148          5.9         3.0          5.1         1.8  Iris-virginica

[149 rows x 5 columns]

In [17]:
dataframe = []

dataframe.append(list(data['PetalLength'].dropna()))
dataframe.append(list(data['PetalWidth'].dropna()))

dataframe.append(list(data['SepalLength'].dropna()))
dataframe.append(list(data['SepalWidth'].dropna()))

dataframe.append(list(data['Class'].dropna()))

dataframe = np.array(dataframe)

In [18]:
dataframe_setosa = []
dataframe_versicolor = []
dataframe_virginica = []

for i in range(4):
    variable1 = []
    variable2 = []
    variable3 = []
    
    dataframe_setosa.append(variable1)
    dataframe_versicolor.append(variable2)
    dataframe_virginica.append(variable3) 

In [19]:
for i , value in enumerate(dataframe[4]):
    
    if value == 'Iris-setosa':
        
        dataframe_setosa[0].append(dataframe[0][i])
        dataframe_setosa[1].append(dataframe[1][i])
        dataframe_setosa[2].append(dataframe[2][i])
        dataframe_setosa[3].append(dataframe[3][i])
        
    elif value == 'Iris-versicolor':
        
        dataframe_versicolor[0].append(dataframe[0][i])
        dataframe_versicolor[1].append(dataframe[1][i])
        dataframe_versicolor[2].append(dataframe[2][i])
        dataframe_versicolor[3].append(dataframe[3][i])
        
    elif value == 'Iris-virginica':
        
        dataframe_virginica[0].append(dataframe[0][i])
        dataframe_virginica[1].append(dataframe[1][i])
        dataframe_virginica[2].append(dataframe[2][i])
        dataframe_virginica[3].append(dataframe[3][i])

In [20]:
def mean(dataframe):
    
    means = []
    
    for i in dataframe:
        value = 0
        for j in i:

            value += float(j)
        value = value / len(i)
        means.append(value)
        
    return means    

In [21]:
means_setosa = mean(dataframe_setosa)
means_versicolor = mean(dataframe_versicolor)
means_virginica = mean(dataframe_virginica)

print("Mean Values Are In Sequence : (Petal Length , Petal Width , Sepal Length , Sepal Width)\n\n")
print("  Setosa : " , means_setosa)
print("  Versicolor : " , means_versicolor)
print("  Virginica : " , means_virginica)

Mean Values Are In Sequence : (Petal Length , Petal Width , Sepal Length , Sepal Width)


  Setosa :  [1.4653061224489796, 0.2448979591836734, 5.004081632653061, 3.416326530612245]
  Versicolor :  [4.26, 1.3259999999999998, 5.936, 2.7700000000000005]
  Virginica :  [5.552, 2.026, 6.587999999999998, 2.9739999999999998]


In [22]:
def z_centered_classwise(feature1 , feature2, feature3 , feature4, mean1, mean2, mean3, mean4):
    
    centered1 , centered2 , centered3 , centered4 = [] , [] , [] , []
    
    for i , value in enumerate(feature1):
        variable1 = float(value) - mean1
        variable2 = float(feature2[i]) - mean2
        variable3 = float(feature3[i]) - mean3
        variable4 = float(feature4[i]) - mean4
        
        centered1.append(variable1)
        centered2.append(variable2)
        centered3.append(variable3)
        centered4.append(variable4)
        
    array = []
    array.append(centered1)
    array.append(centered2)
    array.append(centered3)
    array.append(centered4)

    z = np.array(array)
    z = z.T
    
    return z

In [23]:
def covariance_classwise(feature1 , feature2, feature3, feature4, mean1, mean2, mean3, mean4):
    
    z = z_centered_classwise(feature1 , feature2, feature3, feature4, mean1, mean2, mean3, mean4)
    zT = z.T
    
    result = zT.dot(z)
    result = result / len(feature1)
    
    print("Covariance Matrix X Using Product Formula....\n" , result)
    return result

In [24]:
print("For Setosa : \n")
covariance_setosa = covariance_classwise(dataframe_setosa[0] , dataframe_setosa[1], dataframe_setosa[2], dataframe_setosa[3], means_setosa[0], means_setosa[1], means_setosa[2], means_setosa[3])

For Setosa : 

Covariance Matrix X Using Product Formula....
 [[0.03002082 0.00563932 0.01626406 0.01179092]
 [0.00563932 0.01145356 0.01063307 0.01151187]
 [0.01626406 0.01063307 0.12406497 0.10013744]
 [0.01179092 0.01151187 0.10013744 0.14503957]]


In [25]:
print("For Versicolor : \n")
covariance_versicolor = covariance_classwise(dataframe_versicolor[0] , dataframe_versicolor[1], dataframe_versicolor[2], dataframe_versicolor[3], means_versicolor[0], means_versicolor[1], means_versicolor[2], means_versicolor[3])

For Versicolor : 

Covariance Matrix X Using Product Formula....
 [[0.2164   0.07164  0.17924  0.081   ]
 [0.07164  0.038324 0.054664 0.04038 ]
 [0.17924  0.054664 0.261104 0.08348 ]
 [0.081    0.04038  0.08348  0.0965  ]]


In [26]:
print("For Virginica : \n")
covariance_virginica = covariance_classwise(dataframe_virginica[0] , dataframe_virginica[1], dataframe_virginica[2], dataframe_virginica[3], means_virginica[0], means_virginica[1], means_virginica[2], means_virginica[3])

For Virginica : 

Covariance Matrix X Using Product Formula....
 [[0.298496 0.047848 0.297224 0.069952]
 [0.047848 0.073924 0.048112 0.046676]
 [0.297224 0.048112 0.396256 0.091888]
 [0.069952 0.046676 0.091888 0.101924]]


In [27]:
def multivariate_gaussian(determinant , inverse, k, x, means):
    
    value1 = 1 / ( ( ( (2 * 3.13) ** k ) * determinant ) ** 0.5)
    
    value2 = (-0.5 * ( (x - means).T ) )
    value2.reshape(4,1)
    
    value3 = np.dot(inverse , (x - means))
    
    result = value1 * (2.718 ** np.dot(value2 , value3))
    
    return result

In [28]:
def probability_class(covariance , mean, datapoint):
   
    # update covariance
    for i in range(len(covariance)):
        for j in range(len(covariance[i])):
            if i != j :
                covariance[i][j] = 0    

    # determinant
    determinant = np.linalg.det(covariance)

    # inverse
    inverse = np.linalg.inv(covariance)

    # mean
    means = np.array(mean)
    
    # k 
    k = 4

    # x
    x = np.array(datapoint)
    
    return multivariate_gaussian(determinant , inverse, k, x, means)

In [29]:
datapoint = [6, 4, 5.5, 4]
k = 4

probabilities_classes = []

# Setosa
probabilities_classes.append(0.33 * probability_class(covariance_setosa , means_setosa, datapoint))

# Versicolor
probabilities_classes.append(0.33 * probability_class(covariance_versicolor  , means_versicolor, datapoint))

# Virginica
probabilities_classes.append(0.33 * probability_class(covariance_virginica , means_virginica, datapoint))

In [30]:
if probabilities_classes[0] > probabilities_classes[1] and probabilities_classes[1] > probabilities_classes[2]:
    print("Datapoint Belongs To Class Setosa")
          
elif probabilities_classes[1] > probabilities_classes[0] and probabilities_classes[1] > probabilities_classes[2]:
    print("Datapoint Belongs To Class Versicolor")
          
elif probabilities_classes[2] > probabilities_classes[0] and probabilities_classes[2] > probabilities_classes[1]:
    print("Datapoint Belongs To Class Virginica")

Datapoint Belongs To Class Virginica


Categorize the continuous values and perform the 2 nd task. How well was your
categorization? Did it achieve the same results without categorizing the data?

A friend of yours has just opened a pizza shop and he doesn’t want to you come there
fearing you would eat for free. Somehow you sneak in the shop and you order an 8 inch
pizza , your friend tells you that he doesn’t have an 8 inch pizza but he can give you two
5 inch ones at the same price with the exact same things. As a statistician, should you
be taking that deal? Is that beneficial for you or not? Give statistical reasoning.

In [12]:
r = [5,8]
# applying pie * r ** 2 (formula of area) to find which deal is best

In [13]:
# 2 5 inch pizzas
area1 = 3.14 * (r[0] ** 2)
area1 = area1 + area1
area1

157.0

In [14]:
area2 = 3.14 * (r[1] ** 2)
area2

200.96

In [ ]:
# as area of one 8 inch pizza is more than that of 2 5 inch pizzas, so this deal is not beneficial 